# Generated by Django 3.2.9 on 2021-11-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211115_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
    ]
