# Generated by Django 3.2.9 on 2021-11-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_number_of_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
