# Generated by Django 3.2.9 on 2021-11-22 08:27

import company.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_restaurants',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2), company.validators.digits_only_validators]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True, validators=[company.validators.date_in_future_validator]),
        ),
    ]
